### PR TITLE
Use same rounding mode for glucose in history as everywhere else

### PR DESCRIPTION
**Pull request by dnzxy**
Addresses rounding offset as reported in issue #398

### CODE REVIEW

**Comment by Jon-b-m** [comment]
Example presented in my first post 🙂. 
When entering high manual glucose entries, the displayed amount is different from what you entered, due to the rounding. 

Easiest fix would be use another formatter for manual glucose entries, using the .ceiling rounding rule here. 

Do you want me to fix this for you?

**Comment by dnzxy** [comment]
I read that you were saying really high values, yes, that is still very abstract. High values in mmol/L means 15-20? With decimals or without? Sorry, just trying to be able to reproduce this locally here on my end to then fix it. 

I’m still a bit confused because we are only using the `.ceiling` rounding for this specific glucose formatter in the data table view in the app. All other instances where we have distinct glucose formatters use the `.halfUp` that was introduced here. 

Does this mean that initially, when you fixed this with `.ceiling`, that it was only added in the data table but not for all other controllers where we have glucose formatiertes? So subsequently we are using wrong rounding everywhere else but here? I am also asking this in such detail, because in #398 @dsut4392 reported that the glucoses are correctly rounded and displayed (like in his Dexcom app) everywhere but the data table view. 

Happy to look at this once it is clear where and what needs fixing 😊

**Comment by Jon-b-m** [comment]
I will close this PR and make the fix.  It's quicker than discussion or explaining in detail what you need to do with this PR.

**Comment by dnzxy** [comment]
Clear input will produce clear output. Leaving questions unanswered doesn't.

**Pull request closed without merging**
