### PR TITLE
Move useFPU toggle from FPUConfigRootView to AddCarbsRootView

### PR DESCRIPTION
**Pull request by bjornoleh**
An attempt to make FPU more accessible without "always" being displayed.

The toggle is here more of a clickable button. Currently it is displayed as "Use FPU" with blue text, and when active, it is highlighted with black text on blue background. I am open to suggestions for using different colours, or a different text.

The "Use FPU" text is not localized (I don't know how to do that yet).

### CODE REVIEW

**Comment by bjornoleh** [comment]
IMG_3884

**Comment by Jon-b-m** [comment]
The placement is interesting, but many users don't know what FPU means...

**Comment by bjornoleh** [comment]
Ok, I think I like that, testing "Fat and Protein" now. This is also in the sequence that @GerhardFuehrer suggested, and the same as in "FPU". So perhaps the list of entries should be changed like this, although that is unrelated to this PR

1. Carbs
1. Fat
1. Protein

**Comment by Jon-b-m** [comment]
Yes. You can change this here also if you want to...

**Comment by Jon-b-m** [comment]
You can remove the .foregroundColor from the DecimalTextField. The colour was already declared higher up.

**Comment by bjornoleh** [comment]
Ok. 

Looks pretty good, I think. 

image

**Comment by Jon-b-m** [comment]
Yes, this works I think.

**Comment by Jon-b-m** [comment]
Just some cleaning up in FPUConfigStateModel needed.

**Comment by bjornoleh** [comment]
Ok, perhaps you can do that, and maybe also add the localisation? Haven't figured out that yet.

**Comment by Jon-b-m** [comment]
> Ok, perhaps you can do that, and maybe also add the localisation? Haven't figured out that yet. 

I can't edit your PR directly (I don't think I can). You removed the toggle. So now just remove the variable and stop subscribing to it in fpuConfigStateModel. Then please test If still working. 

The localization I can add later. In another PR.

**Pull request merged**
