### PR TITLE
ISSUE-110 | Sync arrow position with Digital Crown orientation

### PR DESCRIPTION
**Pull request by bashjs**
> Issue: https://github.com/Artificial-Pancreas/iAPS/issues/110

## Changes

- Used `WKInterfaceDevice.current().crownOrientation` to read the position of the Digital Crown
- Changed the help arrow from pointing to the right (or left) to pointing down to avoid confusion when placed next to the `Cancel` button
- Minor View cleanup

## Notes

- These are my first lines of code in Swift
- Xcode Simulator has no toggle to simulate Digital Crown orientation

|`crownOrientation  == .left`|`crownOrientation  == .right`
|-|-
|Screenshot 2023-06-13 at 23 45 01|Screenshot 2023-06-13 at 23 43 46

### CODE REVIEW

**Comment by Jon-b-m** [comment]
Thanks! Did you test this update also on different Watch sizes? The format, like for instance your spaces value, sometimes need special tweaking depending on Watch size.

**Comment by bashjs** [comment]
> Thanks! Did you test this update also on different Watch sizes? The format, like for instance your spaces value, sometimes need special tweaking depending on Watch size.

I tested it on my Ultra. I'll test in other watch simulators today.
What do you think about the shrunk "Cancel" button when the crown is on the left side? 🤔 I couldn't come up with a more elegant variant.

**Comment by Jon-b-m** [comment]
> > Thanks! Did you test this update also on different Watch sizes? The format, like for instance your spaces value, sometimes need special tweaking depending on Watch size.
> 
> What do you think about the shrunk "Cancel" button when the crown is on the left side? 🤔 I couldn't come up with a more elegant variant.

Removing the arrow or changing positions of the cancel button are two other alternatives...

**Comment by Jon-b-m** [comment]
I will merge it now. If we find issues, please be prepared fixing these later with new PRs!

**Pull request merged**
