### PR TITLE
Update HomeRootView.swift

### PR DESCRIPTION
**Pull request by nicolevanelstvandenhoek**
Made a change in the eventualBG icon.

### CODE REVIEW

**Comment by Jon-b-m** [comment]
Do you have a screenshot? I agree the current arrow is too small (and the rounding of eventual BG should only be one fraction digit for mmol/l values), but I'm not certain of this arrow as I haven't tested. Could you please show us?

**Comment by nicolevanelstvandenhoek** [comment]
Hi Jon,
Sorry my late response. Of course, I can show you a screenshot :). Meanwhile, I've made some more changes to the layout. The bottom icons are now also Apple defaults. Additionally, in the 'header view,' I changed the droplet to a 'fuel tank.'

Kind regards, Nicole'



________________________________
Van: Jon B Mårtensson ***@***.***>
Verzonden: zondag 19 november 2023 18:06
Aan: Artificial-Pancreas/iAPS ***@***.***>
CC: Nicole van Elst - van den Hoek ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Artificial-Pancreas/iAPS] Update HomeRootView.swift (PR #353)


Do you have a screenshot? I agree the current arrow is too small (and the rounding of eventual BG should only be one fraction digit for mmol/l values), but I'm not certain of this arrow as I haven't tested. Could you please show us?

**Comment by nicolevanelstvandenhoek** [comment]
Here is the screenshot: 
image

**Comment by Jon-b-m** [comment]
Thanks, but I have a new design coming up where the eventual glucose will be more prominently displayed somewhere else (and using a different arrow). To see before release you can DM me in Discord.

**Pull request closed without merging**
