### PR TITLE
UI/UX improvements: Reworked History and Manual Glucose Dialog, added Non-Pump Insulin Entry, Various other Additions

### PR DESCRIPTION
**Pull request by dnzxy**
## Contents
This PR reworks the entire treatments and glucose history. It contains the following changes
* ~~adds a new flag for non-pump insulin (also uploaded to Nightscout)
image~~
see PR #267 
* adds a new dialog to add non-pump insulin → moved functionality to treatments history(!)
* reworks the manual glucose entry dialog
* adds a toggleable feature to display treatments history in 2 or 3 tabs
   * Three tabs with no coloured dots (= the **default**):
      1. insulin treatments and pump events
      2. carb and FPU entries
      3. glucose
   * Two tabs, i.e. current display
     1. all treatments (insulin, pump events, carbs, FPUs)
     2. glucose
* removes `Add bolus without actually bolusing` functionality from the bolus entry dialog
* changes information display for entire history (alignment of text)
* adds toggle to `Statistics and Home View` settings to switch between 2-tabbed or 3-tabbed history
*  and manual glucose entries
* adds delete dialog to glucose entries, i.e., streamlining it to how treatments are deleted
* removes ⓧ icon from treatments and adds standard iOS swipe-to-delete behaviour
* adds proper descriptive message when deleting FPU entries with the sum of carb equivalents that are to be deleted
* ~~adds title to carb entry view, as it was missing~~
see PR #269 
* ~~streamlines all buttons (centered alignment, same size) for all coming-from-home-view dialogs/views~~
see PR #269 
* ~~fixed display of (temp) basal bars in dark mode on home screen, i.e. has proper blue-ish color now~~ 
see PR #268 
image

## Changes: Before and After
| **Old 2 Tab Layout** | &nbsp; | **New 2 Tab Layout** | &nbsp; |
|--------|--------|--------|--------|
| image | image | image | image |

| **New 3 Tab Layout** | &nbsp; | &nbsp; |
|--------|--------|--------|
| image | image | image |

| **Old Glucose Entry** | **New Glucose Entry** |
|--------|--------|
| image | image |

| **Old "external" Insulin entry in bolus entry** | &nbsp; | &nbsp; |
|--------|--------|--------|
| image | image | image |

| **New Non-Pump Insulin Dialog** | &nbsp; | &nbsp; |
|--------|--------|--------|
| image | image | image | 

| **Old FPU delete alert** | **New FPU delete alert** |
|--------|--------|
| image | image | 

| **New delete treatments/meal action (swipe-to-delete)** | &nbsp; | **Deleting new non-pump insulin (w/ flag)** |
|--------|--------|--------|
| image | image | image |
 
| **Old settings** | **New setting for combining/splitting history view** (toggle disabled = 3 tab view = default) |
|--------|--------|
| image | image |

### CODE REVIEW

**Comment by mountrcg** [comment]
to make SMB triangles:
```
                    if treatment.isSMB ?? false { Image(systemName: "arrowtriangle.down.fill").foregroundColor(treatment.color) }
                    else { Image(systemName: "circle.fill").foregroundColor(treatment.color)
```
at https://github.com/Artificial-Pancreas/iAPS/blob/9ff112e643d35ad0b85ab19a638a62578bb8ad22/FreeAPS/Sources/Modules/DataTable/View/DataTableRootView.swift#L308

**Comment by dnzxy** [comment]
> to make SMB triangles:
> 
> ```
>                     if treatment.isSMB ?? false { Image(systemName: "arrowtriangle.down.fill").foregroundColor(treatment.color) }
>                     else { Image(systemName: "circle.fill").foregroundColor(treatment.color)
> ```
> 
> at
> 
> https://github.com/Artificial-Pancreas/iAPS/blob/9ff112e643d35ad0b85ab19a638a62578bb8ad22/FreeAPS/Sources/Modules/DataTable/View/DataTableRootView.swift#L308

Yes. That would only cover half of it, because it would also make sense in the chart and I wouldn’t want to implement this without further approval by the community - see Discord.

**Comment by dnzxy** [comment]
After having received comprehensive feedback by @Jon-b-m I have made and just pushed the following changes to the PR:

**Placement and Styling for Dialog Buttons**
- Moved buttons from placement as `navigationItems` to below the `Picker` elements and above the `List`
- Changed styling from button with text and icon to an icon only button depicting a `(+)`

| Current iAPS `main` | Initial PR Button Style | \*new\* Current Button Style |
|--------|--------|--------|
|  image | image | image |


**History settings under "Statistics and Home View"**
- Moved toggle from first option into section of its own
- Added more descriptive text around setting to make it clear what the default is and what the setting toggles

| Current iAPS `main` | Initial Settings Style | \*new\* Current Settings Style |
|--------|--------|--------|
| image | image | image |

**Comment by AndreasStokholm** [comment]
**Placement and Styling for Dialog Buttons**

_Positioning_
I am split on the new `+` button below the Picker element. On the one hand it makes it more reachable for one handed use, but on the other it feels very out of place there when the action being performed is opening a new sheet (eg navigating).

 I also somewhat dislike the jumping of the list below when switching between `Insulin`, `Meals`, and `Glucose`, since `Meals` does not have add functionality.

_Styling_
I miss having some text explaining the action when tapping the button. I suggest adding `External Insulin` and `Glucose` before the `+`.

**History settings under "Statistics and Home View"**

I think this is very clear and easier to understand what the toggle now does 👍

**Comment by bjornoleh** [comment]
I agree that it is not quite descriptive with only a + (without any text), especially for the case when “Combine Treatments in History” is toggled on, since you can only add non-pump insulin, and not carbs (or temp targets and suspend/resume, which are also displayed here). I would vote for adding some text like “Add Non-pump Insulin” and “Add Manual Glucose”. Preferably aligned with the right edge. 

Regarding the style and colour, I find the gray plus symbol a little too inconspicuous, to the point that I would expect some users to not notice it at all. Using the blue colour that was used before would help in my opinion. 

I don’t have too strong opinions on the placement (top row or one step down as is currently used in the PR).

**Comment by tqb43** [comment]
I love all the updates you've been making, Dan. My personal opinion on the latest iteration...

_Positioning_
I like the position of the + under the Picker element. However, I think we need to keep the descriptive labels, it's not really clear what the button is without it. We don't want people guessing what different buttons do. 

_Statistics Menu_
I like the option to combine the treatment views, however I don't think it makes sense for the toggle to be under 'Statistics'. Maybe under preferences, or even under the history view itself?

**Comment by mountrcg** [comment]
I have been using it for the last couple of weeks, it looks and works great! I like the blue add  non-pump insulin and glucose better than the +, and actually kept using it this way. I would be happy, if it gets merged.

**Comment by Jon-b-m** [comment]
Please brake this down in smaller PRs. The more specific the better.

**Comment by Jon-b-m** [comment]
Preferably remove current and create new smaller.

**Comment by dnzxy** [comment]
> Please brake this down in smaller PRs. The more specific the better.
Preferably remove current and create new smaller.

I'll try to split it. Suggestion for PRs:

1. Changes information display for entire history (alignment of text)
2. Reworks the manual glucose
   * sheet view for entry dialog
   * adds delete dialog to glucose entries, i.e., streamlining it to how treatments are deleted
3. non-pump insulin dialog
   * adds a new dialog to add non-pump insulin → moved functionality to treatments history(!)
   * removes Add bolus without actually bolusing functionality from the bolus entry dialog
5. rework deletion for treatments
   * removes ⓧ icon from treatments and adds standard iOS swipe-to-delete behaviour
   * adds proper descriptive message when deleting FPU entries with the sum of carb equivalents that are to be deleted
6. new treatment layout
   * adds a toggleable feature to display treatments history in 2 or 3 tabs
   * adds toggle to Statistics and Home View settings to switch between 2-tabbed or 3-tabbed history and manual glucose entries

Is that okay?

**Pull request closed without merging**
