### PR TITLE
Fastlane/GH build improvements: Add sync action and keepalive action, align with Loop dev improvements

### PR DESCRIPTION
**Pull request by bjornoleh**

### CODE REVIEW

**Comment by Jon-b-m** [comment]
How does the keep alive empty commit look like? Did you test this PR fully  before submitting?

**Comment by bjornoleh** [comment]
There are some points to discuss once you have seen how it works. I might make some adjustments after discussing, so no rush in merging this just yet. You can test it in your private fork first if you like (you would have to change the default branch to be able to run the new update.yml workflow), or wait until I have the time to walk you through it. 

I may be able to keep everything in the build_iAPS.yml, it depends on how you feel about some consequences of that. 

Let me get back to you in a PM when I have the time.

**Comment by Jon-b-m** [comment]
Get back when you have tested it. It's a bad idea submitting before testing.

**Comment by bjornoleh** [comment]
> How does the keep alive empty commit look like? Did you test this PR fully before submitting?

The keep alive commits look like this:

https://github.com/bjornoleh/LoopWorkspace/commit/da41bf548213d18e4389c0a3ce6df83020784fcf

**Comment by bjornoleh** [comment]
And the sync action will default to a fast forward, if possible:
image

**Comment by bjornoleh** [comment]
If there is divergent local history, a merge commit will be inserted. This is general git pull behaviour, as docmented here:
https://git-scm.com/docs/git-pull

image

**Comment by Jon-b-m** [comment]
I agree with Pete Schwamb's comments/requests. Better to compare with last build date instead of scheduling same build date every month, to only build when necessary. Changing commit nr is also not ideal, since I use this for troubleshooting.

**Comment by Jon-b-m** [comment]
Is this ready to be merged now?

**Comment by bjornoleh** [comment]
Hi, eventually, we found a way to do this that was acceptable to Loop devs. Some additional refinements have been added, and are about to be wrapped up now (a new Loop release is imminent). Once everything is settled, the current implementation in Loop will be propagated to the other projects. This process has taken forever, but seems to come to an end now.

So just hold on a little longer please :-)

@dnzxy

**Comment by dnzxy** [comment]
Thanks for the tag @bjornoleh 😊 

We can offer a vastly improved validation workflow for now, that has been merged into LoopCaregiver, will be merged soon into LoopFollow dev (and probably into main, too), and are pending merge to Loop via LoopWorkspace PR86. They further improve what was moved it to Loop with LoopWorkspace PR77. I‘ve told the guys over at xDrip4iOS the same. 

The automatic build improvements are almost there, I‘d ask for just a tiny bit more patience for those. We found a great way to do both monthly scheduled builds and builds around changes. I hope they will be to your satisfaction, @Jon-b-m 😊

**Comment by Jon-b-m** [comment]
Thanks a lot @bjornoleh and @dnzxy. Will these new changes work with existing fastlane configurations (forks)?

**Comment by bjornoleh** [comment]
There should be no breaking changes. There are a couple of more changes coming, hopefully today. Will ping you when it's ready for merging.

**Comment by dnzxy** [comment]
This should not bring any breaking changes to existing builds. Everything is build on the iAPS user having `workflow` permissions added to their `GH_PAT`. If they haven’t, no automation is enabled and manual build works as they are used to (with many added validations with more descriptive errors). 

There are some minor changes that should make their way in probably today and I think Bjørn will give his final go when it’s ready to merge.

**Comment by Jon-b-m** [comment]
Will merge as soon as you think it's ready

**Comment by bjornoleh** [comment]
This PR should be good to go now. This brings the workflows, Fastfile and also Fastlane version and other dependencies as specified in Gemfile.lock in line with the state of things in Loop dev.

The users fork of iAPS will be synced with Artificial-Pancreas/iAPS before building if the user sets a 'SCHEDULED_SYNC' repository variable to 'true'.

**Pull request merged**
