### PR TITLE
autotune view - show current basal rates

### PR DESCRIPTION
**Pull request by yurique**
<details>
  <summary>screenshot:</summary>
  
image

</details>

### CODE REVIEW

**Comment by Jon-b-m** [comment]
Thanks. I think it would look slightly cleaner without seconds  in first column and with the second column (…->) aligned as leading.

**Comment by yurique** [comment]
I'll give it a shot!

**Comment by yurique** [comment]
I tried changing the `rateFormatter` to always include 2 fraction digits - it did help align the numbers a bit, but it's still not perfect (since it's not a fixed-width font).

Otherwise I'm not sure how to make the whole thing to behave like a table (so that I could align the "columns" perfectly), without making the widths fixed - which would probably be a bad idea.

Here's how it looks like:

<details>
  <summary>screenshot</summary>

image

</summary>

**Comment by Jon-b-m** [comment]
Looks good 👍. Yes iOS 16 is required. And iAPS has some SwiftUI code which is only used when using iOS 17+.

**Comment by Jon-b-m** [comment]
Do we perhaps need a total also? To compare the total autotuned with normal rates?

**Comment by yurique** [comment]
Makes sense!
 I'll add it a bit later.

**Comment by yurique** [comment]
<details>
  <summary>show current total</summary>

image

</details>

<details>
  <summary>seems to match what's displayed in the profile editor</summary>

image

</details>

**Comment by Jon-b-m** [comment]
Accepted.

**Pull request merged**
