### PR TITLE
fix importing settings from Nightscout

### PR DESCRIPTION
**Pull request by MikePlante1**
Before this PR, two settings were not imported from Nightscout correctly for me.
My 95 mg/dL target glucose got imported as 72 mg/dL (the lowest allowed)
My 58mg/dL ISF got imported as 9 mg/dL

After applying this PR and building to a fresh now simulator, my settings were imported correctly.

### CODE REVIEW

**Comment by Jon-b-m** [comment]
Ok, did you test with both configured glucose units in iAPS?

**Comment by MikePlante1** [comment]
I only tested with mg/dL in iAPS (latest dev, and then latest dev + this PR)

I did test mmol/L in a different fork, and it worked fine after applying the PR as well, but I used someone else's NS account for that so I couldn't use it to test iAPS.

**Comment by Jon-b-m** [comment]
So this needs some more testing by more users, with both units.

**Comment by MikePlante1** [comment]
Should be a pretty quick test in a simulator if you find some willing testers.

For mmol/L, though, the logic is unchanged. The only changes in this PR are replacing the 3 ternary operators with the default for mmol/L users.

**Comment by Jon-b-m** [comment]
I've tested now. As mentioned this only affect mg/dl users. 
Thanks for PR. Will merge

**Pull request merged**
