### PR TITLE
Support the newer libre 2 plus European sensors.

### PR DESCRIPTION
**Pull request by Jon-b-m**

### CODE REVIEW

**Comment by Crystalflame66** [comment]
Happy to support in any way I can. 
What would be required of me to assist? 

Thank you.

**Comment by Jon-b-m** [comment]
> I may need some assistance with how to run a branch with the Libre Plus Sensors in iAPS. I'm not very Github savy so it's a new world to me!
> 
> I am happy to follow any instructions on running a branch and feeding back. I do have one spare Plus sensor so I can try with that when I get round to it.

If you’re building with Xcode you can make a new clone in MacOS terminal:
git clone --branch=librePlus https://github.com/artificial-pancreas/iaps.git
cd iaps
xed .

Or if you already have an existing iAPS project open in Xcode you can switch branch using the Xcode source code navigator (the second symbol from the left, to the right hand side of the file navigator). In source code navigator right click Origin/librePlus and choose “Switch” to check out this branch. Then after eventual signing you can build as usual.

**Comment by Crystalflame66** [comment]
Thank you- I believe i built iAPS via the browser build method. Is there any way to work around this method of building??

**Comment by Jon-b-m** [comment]
> Thank you- I believe i built iAPS via the browser build method. Is there any way to work around this method of building??

You can build any branch via the browser method. To build "librePlus" branch: 
1. Select your dev branch in your fork,
2.  Create a new branch named "librePlus
3.  Tap Sync to fetch upstream commits.
4. Now you can build as usual using GitHub Actions, just select "librePlus" before tapping the green button.

**Comment by Crystalflame66** [comment]
> > Thank you- I believe i built iAPS via the browser build method. Is there any way to work around this method of building??
> 
> You can build any branch via the browser method. To build "librePlus" branch:
> 
> 1. Select your dev branch in your fork,
> 2. Create a new branch named "librePlus
> 3. Tap Sync to fetch upstream commits.
> 4. Now you can build as usual using GitHub Actions, just select "librePlus" before tapping the green button.


Thank you- would there be an opportunity to remote in and talk me through at all? I appreciate you are very busy; however, i am just really conscious of doing something incorrectly. I did try and follow the instructions above which seems to play ball initially- however all builds are now failing including my main IAPS build. Just worried this will impact my IAPS that i am currently using. Any support i can have to review this and be guided would really be appreciated. I do want to help but i need support from experts to ensure i am setting things up correctly without causing issues with my existing settings :(

**Comment by Jon-b-m** [comment]
> > > Thank you- I believe i built iAPS via the browser build method. Is there any way to work around this method of building??
> > 
> > 
> > You can build any branch via the browser method. To build "librePlus" branch:
> > 
> > 1. Select your dev branch in your fork,
> > 2. Create a new branch named "librePlus
> > 3. Tap Sync to fetch upstream commits.
> > 4. Now you can build as usual using GitHub Actions, just select "librePlus" before tapping the green button.
> 
> Thank you- would there be an opportunity to remote in and talk me through at all? I appreciate you are very busy; however, i am just really conscious of doing something incorrectly. I did try and follow the instructions above which seems to play ball initially- however all builds are now failing including my main IAPS build. Just worried this will impact my IAPS that i am currently using. Any support i can have to review this and be guided would really be appreciated. I do want to help but i need support from experts to ensure i am setting things up correctly without causing issues with my existing settings :(

Of you add me as “contributor” in your GitHub iaps fork settings I think I can set this up for you.

**Comment by Crystalflame66** [comment]
> > > > Thank you- I believe i built iAPS via the browser build method. Is there any way to work around this method of building??
> > > 
> > > 
> > > You can build any branch via the browser method. To build "librePlus" branch:
> > > 
> > > 1. Select your dev branch in your fork,
> > > 2. Create a new branch named "librePlus
> > > 3. Tap Sync to fetch upstream commits.
> > > 4. Now you can build as usual using GitHub Actions, just select "librePlus" before tapping the green button.
> > 
> > 
> > Thank you- would there be an opportunity to remote in and talk me through at all? I appreciate you are very busy; however, i am just really conscious of doing something incorrectly. I did try and follow the instructions above which seems to play ball initially- however all builds are now failing including my main IAPS build. Just worried this will impact my IAPS that i am currently using. Any support i can have to review this and be guided would really be appreciated. I do want to help but i need support from experts to ensure i am setting things up correctly without causing issues with my existing settings :(
> 
> If you add me as “collaborator” in your GitHub iaps fork settings I think I can set this up for you.

**Thank you! I believe i have sent an invite to you now... please do let me know if you receive this!**

**Comment by Jon-b-m** [comment]
> > > > > Thank you- I believe i built iAPS via the browser build method. Is there any way to work around this method of building??
> > > > 
> > > > 
> > > > You can build any branch via the browser method. To build "librePlus" branch:
> > > > 
> > > > 1. Select your dev branch in your fork,
> > > > 2. Create a new branch named "librePlus
> > > > 3. Tap Sync to fetch upstream commits.
> > > > 4. Now you can build as usual using GitHub Actions, just select "librePlus" before tapping the green button.
> > > 
> > > 
> > > Thank you- would there be an opportunity to remote in and talk me through at all? I appreciate you are very busy; however, i am just really conscious of doing something incorrectly. I did try and follow the instructions above which seems to play ball initially- however all builds are now failing including my main IAPS build. Just worried this will impact my IAPS that i am currently using. Any support i can have to review this and be guided would really be appreciated. I do want to help but i need support from experts to ensure i am setting things up correctly without causing issues with my existing settings :(
> > 
> > 
> > If you add me as “collaborator” in your GitHub iaps fork settings I think I can set this up for you.
> 
> **Thank you! I believe i have sent an invite to you now... please do let me know if you receive this!**

Yes. I’ve created a dev and librePlus branch for you now. I can now build for you but I get an error that your Bundle ID isn’t registered with Apple Connect. Did you create a custom APP_IDENTIFIER repo variable perhaps?

**Comment by Crystalflame66** [comment]
> > > > > > Thank you- I believe i built iAPS via the browser build method. Is there any way to work around this method of building??
> > > > > 
> > > > > 
> > > > > You can build any branch via the browser method. To build "librePlus" branch:
> > > > > 
> > > > > 1. Select your dev branch in your fork,
> > > > > 2. Create a new branch named "librePlus
> > > > > 3. Tap Sync to fetch upstream commits.
> > > > > 4. Now you can build as usual using GitHub Actions, just select "librePlus" before tapping the green button.
> > > > 
> > > > 
> > > > Thank you- would there be an opportunity to remote in and talk me through at all? I appreciate you are very busy; however, i am just really conscious of doing something incorrectly. I did try and follow the instructions above which seems to play ball initially- however all builds are now failing including my main IAPS build. Just worried this will impact my IAPS that i am currently using. Any support i can have to review this and be guided would really be appreciated. I do want to help but i need support from experts to ensure i am setting things up correctly without causing issues with my existing settings :(
> > > 
> > > 
> > > If you add me as “collaborator” in your GitHub iaps fork settings I think I can set this up for you.
> > 
> > 
> > **Thank you! I believe i have sent an invite to you now... please do let me know if you receive this!**
> 
> Yes. I’ve created a dev and librePlus branch for you now. I can now build for you but I get an error that your Bundle ID isn’t registered with Apple Connect. Did you create a custom APP_IDENTIFIER repo variable perhaps?


Thanks so much! That's wonderful- really appreciate all your help. That is very strange... my Bundle ID should be registered with Apple Developer Connect? Happy to show a screen shot if this helps at all? Or if you can guide me where to check & add if needed on Apple Connect? I recall registering it through Apple Connect though when i built IAPS... this was a while back and i was literally following instructions to the word at the time; so please forgive me for not knowing where to navigate and what to check.

**Comment by Jon-b-m** [comment]
> > > > > > > Thank you- I believe i built iAPS via the browser build method. Is there any way to work around this method of building??
> > > > > > 
> > > > > > 
> > > > > > You can build any branch via the browser method. To build "librePlus" branch:
> > > > > > 
> > > > > > 1. Select your dev branch in your fork,
> > > > > > 2. Create a new branch named "librePlus
> > > > > > 3. Tap Sync to fetch upstream commits.
> > > > > > 4. Now you can build as usual using GitHub Actions, just select "librePlus" before tapping the green button.
> > > > > 
> > > > > 
> > > > > Thank you- would there be an opportunity to remote in and talk me through at all? I appreciate you are very busy; however, i am just really conscious of doing something incorrectly. I did try and follow the instructions above which seems to play ball initially- however all builds are now failing including my main IAPS build. Just worried this will impact my IAPS that i am currently using. Any support i can have to review this and be guided would really be appreciated. I do want to help but i need support from experts to ensure i am setting things up correctly without causing issues with my existing settings :(
> > > > 
> > > > 
> > > > If you add me as “collaborator” in your GitHub iaps fork settings I think I can set this up for you.
> > > 
> > > 
> > > **Thank you! I believe i have sent an invite to you now... please do let me know if you receive this!**
> > 
> > 
> > Yes. I’ve created a dev and librePlus branch for you now. I can now build for you but I get an error that your Bundle ID isn’t registered with Apple Connect. Did you create a custom APP_IDENTIFIER repo variable perhaps?
> 
> Thanks so much! That's wonderful- really appreciate all your help. That is very strange... my Bundle ID should be registered with Apple Developer Connect? Happy to show a screen shot if this helps at all? Or if you can guide me where to check & add if needed on Apple Connect? I recall registering it through Apple Connect though when i built IAPS... this was a while back and i was literally following instructions to the word at the time; so please forgive me for not knowing where to navigate and what to check.
> 
> I have had a look at the Apple Connect> Apps> General >App Information and there is a bundle ID incorporated within the iAPS app i built at the time.

OK, please look at these instructions in the section named “Missing Certificate”. You have the same error message https://loopkit.github.io/loopdocs/browser/bb-errors/#annotation-without-clear-message-certificates

**Comment by Crystalflame66** [comment]
> > > > > > > > Thank you- I believe i built iAPS via the browser build method. Is there any way to work around this method of building??
> > > > > > > 
> > > > > > > 
> > > > > > > You can build any branch via the browser method. To build "librePlus" branch:
> > > > > > > 
> > > > > > > 1. Select your dev branch in your fork,
> > > > > > > 2. Create a new branch named "librePlus
> > > > > > > 3. Tap Sync to fetch upstream commits.
> > > > > > > 4. Now you can build as usual using GitHub Actions, just select "librePlus" before tapping the green button.
> > > > > > 
> > > > > > 
> > > > > > Thank you- would there be an opportunity to remote in and talk me through at all? I appreciate you are very busy; however, i am just really conscious of doing something incorrectly. I did try and follow the instructions above which seems to play ball initially- however all builds are now failing including my main IAPS build. Just worried this will impact my IAPS that i am currently using. Any support i can have to review this and be guided would really be appreciated. I do want to help but i need support from experts to ensure i am setting things up correctly without causing issues with my existing settings :(
> > > > > 
> > > > > 
> > > > > If you add me as “collaborator” in your GitHub iaps fork settings I think I can set this up for you.
> > > > 
> > > > 
> > > > **Thank you! I believe i have sent an invite to you now... please do let me know if you receive this!**
> > > 
> > > 
> > > Yes. I’ve created a dev and librePlus branch for you now. I can now build for you but I get an error that your Bundle ID isn’t registered with Apple Connect. Did you create a custom APP_IDENTIFIER repo variable perhaps?
> > 
> > 
> > Thanks so much! That's wonderful- really appreciate all your help. That is very strange... my Bundle ID should be registered with Apple Developer Connect? Happy to show a screen shot if this helps at all? Or if you can guide me where to check & add if needed on Apple Connect? I recall registering it through Apple Connect though when i built IAPS... this was a while back and i was literally following instructions to the word at the time; so please forgive me for not knowing where to navigate and what to check.
> > I have had a look at the Apple Connect> Apps> General >App Information and there is a bundle ID incorporated within the iAPS app i built at the time.
> 
> OK, please look at these instructions in the section named “Missing Certificate”. You have the same error message https://loopkit.github.io/loopdocs/browser/bb-errors/#annotation-without-clear-message-certificates

Thank you very much for your direction and support. I will I have a look and try and work through this when I get a moment away from work! Thanks again for your continued support :)

**Comment by Crystalflame66** [comment]
Hi Jon,

I am still having trouble with my build. I have even gone to the effort of restarting from scratch and now can't get passed verifying secrets which is really odd as i have done this so many times. I just cannot understand why it won't play ball. Until i am able to resolve the issues with my build- i won't be able to test the LibrePlus branch. 

Everything seemed it was building fine yesterday until the last bit.
Today nothing seems to be going through- even the secrets which is incredibly frustrating. I have re-entered the 4 or 5 times and still getting the same error. Any ideas what i am doing wrong?!

**Comment by francesc0-cgm** [comment]
Anyone have tried it and get a fsl2 plus working? I ported this code on autoisf 3.6.6 and i have connection issue loop issue

https://github.com/user-attachments/assets/aea9d438-4c11-497f-9d29-cd9b6783726a

**Comment by Jon-b-m** [comment]
> Has anyone tried it and get a fsl2 plus working? I ported this code on autoisf 3.6.6 and i have connection issue loop issue
> 
>  RPReplay_Final1725359290.mov

Thanks. I've now  pushed the missing sensor type string, suggested and tested by you.

**Comment by Crystalflame66** [comment]
Hello,

I did manage to get hold of a FS2 Plus sensor and tried running the Libre Plus branch  and pairing with no success unfortunately.  It provides the option to connect the sensor but when you scan it,  the sensor scans but iaps doesn't seem to recognise it and keeps providing prompts to scan the sensor. It advises to check that the sensor has completed warming up (which it had).

I continued to try but it just wasn't moving forward so unfortunately had to disconnect and waste a sensor as a result.

I don't have any more FS2 Plus sensors to work with as I've been put back on the FS2 sensor for now. However, I am worried for when the FS2 sensor is no longer available.

I am so sorry I haven't had any positive updates to show with my attempt 😞

**Comment by Jon-b-m** [comment]
> Hello,
> 
> I did manage to get hold of a FS2 Plus sensor and tried running the Libre Plus branch and pairing with no success unfortunately. It provides the option to connect the sensor but when you scan it, the sensor scans but iaps doesn't seem to recognise it and keeps providing prompts to scan the sensor. It advises to check that the sensor has completed warming up (which it had).
> 
> I continued to try but it just wasn't moving forward so unfortunately had to disconnect and waste a sensor as a result.
> 
> I don't have any more FS2 Plus sensors to work with as I've been put back on the FS2 sensor for now. However, I am worried for when the FS2 sensor is no longer available.
> 
> I am so sorry I haven't had any positive updates to show with my attempt 😞

I have reports from other users telling this now works with Libre 2 plus. This has therefore already been merged into dev branch. Are you running the latest dev branch or librePlus? There was an update to librePlus some time ago which sorted out some mixed up CGM types.

**Comment by Crystalflame66** [comment]
Thanks Jon- it's likely I was running an older version of the branch then. Would it be possible to link me to the updated branch as I am sure thay will be why I've had issues! (Re: Libre Plus- are you also referring to the actual Libre Plus app? I believe I am running the latest version). The branch however is likely to be where I've gone wrong!

That's really great news to hear!

**Comment by Crystalflame66** [comment]
Thank you Jon. I'm happy to wait till version 5.6. (I think I'm on version 5.4 now but it automatically updates everytime the version updates on iAPS). 

Thank you! Great news 👏

**Pull request merged**
