### PR TITLE
Fix rounding 

### PR DESCRIPTION
**Pull request by mountrcg**
There was still the issue with 2 digits in the DateTable for tempTargets
also another place in TT state model

### CODE REVIEW

**Comment by Jon-b-m** [comment]
No. It is rounded  in a closure higher up already. Thus this PR serves no purpose

**Comment by mountrcg** [comment]
@Jon-b-m try to put in 8.1mmol/L as temp target and when switch to mg/dL.

Simulator Screen Shot - Dev iPhone 13mini - 2023-03-25 at 13 42 40 
It will also be saved with one decimal im mg/dL.

This commit fixes this and also that the data table displays converted TT with 2 decimals.

Simulator Screen Shot - Dev iPhone 13mini - 2023-03-25 at 13 39 54

**Comment by Jon-b-m** [comment]
I tested current code. It converts fine already mmol/L <-> mg/dl. Your code is outdated. You need to sync updates.

**Comment by mountrcg** [comment]
I did the screens just now with current dev.
But I guess you worked on the TT thing and fixed with that. Did you fix the History Table too?

**Pull request closed without merging**
