### PR TITLE
Add three tab layout to history and UI/UX settings

### PR DESCRIPTION
**Pull request by dnzxy**
## Description
This PR adds a three tab layout to the iAPS history and a respective setting to configure the layout.
This feature was initially proposed as part of #236.

## Contents
* Adds a third tab to iAPS history (customizable, see next bullet point)
* Adds new setting to iAPS > Settings > UI/UX Settings in picker style for users to select their preferred history layout 
   * If layout is configured to "3 Tabs", history will show "Insulin", "Meals" and "Glucose"
   * If layout is configured to "2 Tabs" (=default), history will show "Treatments" and "Glucose
* Some very minor refactoring around conditional filters in `DataTableRootView` to make various statements more concise

Side note: A picker was chosen as it feels more intuitive to select the preferred layout ("As a user, I want my history layout to be..."), instead of having to toggle between layout "2 Tabs" or "3 Tabs". The user does not want to enable or disable something, but select between two choices.

## Screenshots
These screenshots show the layout configured to "3 Tabs". The default layout (=2 tabs) was not changed in any way or form.

| 3 Tabs + Settings | &nbsp; | &nbsp; |
|--------|--------|--------|
| image | image | image |
| image | image | &nbsp; | 

For completeness:
| 2 Tabs | &nbsp; | &nbsp; |
|--------|--------|--------|
| image | image | &nbsp; |

### CODE REVIEW

**Comment by bjornoleh** [comment]
I had a brief look. This seems ok to me. But wondering if you would consider displaying the coloured blobs for meals too, to easier discriminate between carbs and FPU carb equivalents? This would make it more coherent the graph and the Insulin tab.

**Comment by dnzxy** [comment]
> I had a brief look. This seems ok to me. But wondering if you would consider displaying the coloured blobs for meals too, to easier discriminate between carbs and FPU carb equivalents? This would make it more coherent the graph and the Insulin tab.
Thanks for the feedback :) Regarding your suggestion: Current `dev` displays the same colored dot for both carb and FPU, the FPU dot just has a bit of opacity. So in history you would end up with the same yellow-ish dot. Does that make things easier discernable? Happy to add this.

See quick fiddle below:

| Dark mode | Light mode |
|--------|--------|
| image | image |

**Comment by bjornoleh** [comment]
Thanks, this is what I had in mind. I think it’s good for both consistency and readability.

**Comment by dnzxy** [comment]
@bjornoleh consistent colored dot added for all tab views except glucose  👍

**Comment by Jon-b-m** [comment]
It's looking OK, but I just had a crash with your previous PR with swipe to delete glucose entries when using the simulator. I will try to find out why before merging this PR, as there seems some refactoring is needed . Don't have any more info right now, But I'll have to look at it after Christmas.

**Comment by dnzxy** [comment]
@Jon-b-m Would you care to elaborate why this was closed without any further comment or change request?

**Comment by Jon-b-m** [comment]
Hmm. I didn't close it... Mistake perhaps

**Comment by dnzxy** [comment]
> Hmm. I didn't close it... Mistake perhaps

Maybe because you deleted the branch the PR was targeted to GH auto-closed it. Would you like me to re-open it targeting to new `alpha` or not? 😊

**Pull request closed without merging**
